=== NHSDigital/nhs-notify-client-config/packages/schemas/json/client-mutated-1.0.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "ClientMutatedEvent",
  "type": "object",
  "properties": {
    "dataschema": {
      "type": "string",
      "pattern": "^https:\\/\\/notify\\.nhs\\.uk\\/events\\/schemas\\/client-mutated-1.\\d+\\.\\d+\\.json$"
    },
    "dataschemaversion": {
      "type": "string",
      "pattern": "^1\\.\\d+\\.\\d+$"
    },
    "type": {
      "type": "string",
      "const": "uk.nhs.notify.config.ClientMutated"
    },
    "id": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "specversion": {
      "type": "string",
      "const": "1.0"
    },
    "subject": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "datacontenttype": {
      "type": "string",
      "const": "application/json"
    },
    "plane": {
      "type": "string",
      "const": "control"
    },
    "data": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "senderOdsCode": {
          "type": "string"
        },
        "quota": {
          "description": "ClientQuota",
          "type": "object",
          "properties": {
            "tps": {
              "type": "number"
            },
            "periodSeconds": {
              "type": "number"
            },
            "initialQuota": {
              "type": "number"
            }
          },
          "required": [
            "tps",
            "periodSeconds",
            "initialQuota"
          ],
          "additionalProperties": false
        },
        "meshMailbox": {
          "description": "MeshMailbox",
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "mailboxId": {
              "type": "string"
            },
            "workflowIdSuffix": {
              "type": "string"
            },
            "workflowIdReceiveRequestAck": {
              "type": "string"
            },
            "workflowIdCompletedRequestItemsReport": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "mailboxId"
          ],
          "additionalProperties": false
        },
        "apimApplication": {
          "description": "ApimApplication",
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "apimId": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "apimId"
          ],
          "additionalProperties": false
        },
        "govuknotifyAccount": {
          "description": "GovuknotifyAccount",
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "default": {
              "type": "boolean"
            }
          },
          "required": [
            "id",
            "name",
            "default"
          ],
          "additionalProperties": false
        },
        "featureFlags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rfrCodes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "suppressionFilters": {
          "type": "array",
          "items": {
            "description": "SuppressionFilter",
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "pattern": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "pattern"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "id",
        "name",
        "featureFlags",
        "rfrCodes",
        "suppressionFilters"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "dataschema",
    "dataschemaversion",
    "type",
    "id",
    "source",
    "specversion",
    "subject",
    "time",
    "datacontenttype",
    "plane",
    "data"
  ],
  "additionalProperties": false
}

=== NHSDigital/nhs-notify-client-config/packages/schemas/src/__tests__/testData/validClientDetails.json
{
  "id": "23f1f09c-a555-4d9b-8405-0b33490bc920",
  "source": "//notify.nhs.uk/app/nhs-notify-config-dev/main",
  "specversion": "1.0",
  "subject": "00f3b388-bbe9-41c9-9e76-052d37ee8988",
  "time": "2025-08-28T08:45:00.000Z",
  "datacontenttype": "application/json",
  "plane": "control",
  "type": "uk.nhs.notify.config.ClientMutated",
  "dataschema": "https://notify.nhs.uk/events/schemas/client-mutated-1.0.0.json",
  "dataschemaversion": "1.0.0",
  "data": {
    "id": "00f3b388-bbe9-41c9-9e76-052d37ee8988",
    "name": "Test Client",
    "senderOdsCode": "X26",
    "quota": {
      "tps": 5,
      "periodSeconds": 60,
      "initialQuota": 300
    },
    "apimApplication": {
      "id": "255adc65-fb02-4570-b8f7-d99198eb0b49",
      "apimId": "test-apim-id"
    },
    "govuknotifyAccount": {
      "id":"70a4c0fc-c9d4-4917-849d-2554e83af13a",
      "name": "Test Client (INT)",
      "default": true
    },
    "featureFlags": [],
    "rfrCodes": [],
    "suppressionFilters": []
  }
}
